input {
  file {
    path => "/var/log/waf/access.log"
    start_position => "beginning"
    type => "apache_access"
  }
  file {
    path => "/var/log/waf/modsec_audit.log"
    start_position => "beginning"
    type => "modsecurity"
  }
}

filter {
  if [type] == "apache_access" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
  }

  if [type] == "modsecurity" {
    grok {
      match => { "message" => "\[id \"%{NUMBER:rule_id}\"\]" }
      tag_on_failure => []
    }
    grok {
      match => { "message" => "\[msg \"%{DATA:attack_message}\"\]" }
      tag_on_failure => []
    }
    grok {
      match => { "message" => "\[uri \"%{DATA:attacked_uri}\"\]" }
      tag_on_failure => []
    }

    if "Access denied" in [message] {
      mutate { add_field => { "action" => "BLOCKED" } }
    } else if "Warning" in [message] {
      mutate { add_field => { "action" => "DETECTED" } }
    }

    if "SQLi" in [message] or "SQL Injection" in [message] {
      mutate { add_field => { "attack_type" => "SQL Injection" } }
    } else if "XSS" in [message] {
      mutate { add_field => { "attack_type" => "XSS" } }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "security-logs-%{+YYYY.MM.dd}"
  }
}
